In [1]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential 

In [14]:
voc_size=10000

In [15]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [16]:
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5286, 4237, 5954, 2204],
 [5286, 4237, 5954, 7607],
 [5286, 573, 5954, 4],
 [5559, 6819, 2915, 8931, 6532],
 [5559, 6819, 2915, 8931, 1977],
 [3247, 5286, 4837, 5954, 7753],
 [9842, 7096, 4196, 8931]]

In [17]:
import numpy as np

In [18]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5286 4237 5954 2204]
 [   0    0    0    0 5286 4237 5954 7607]
 [   0    0    0    0 5286  573 5954    4]
 [   0    0    0 5559 6819 2915 8931 6532]
 [   0    0    0 5559 6819 2915 8931 1977]
 [   0    0    0 3247 5286 4837 5954 7753]
 [   0    0    0    0 9842 7096 4196 8931]]


In [19]:
## feature representation
dim=10

In [23]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.build(input_shape=(None, sent_length))
model.compile('adam','mse')

In [24]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [22]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 259ms/step


array([[[-0.04936626, -0.04873944, -0.01763833, -0.00664655,
          0.03444407, -0.00357095, -0.04538939, -0.0094085 ,
          0.03327018,  0.013641  ],
        [-0.04936626, -0.04873944, -0.01763833, -0.00664655,
          0.03444407, -0.00357095, -0.04538939, -0.0094085 ,
          0.03327018,  0.013641  ],
        [-0.04936626, -0.04873944, -0.01763833, -0.00664655,
          0.03444407, -0.00357095, -0.04538939, -0.0094085 ,
          0.03327018,  0.013641  ],
        [-0.04936626, -0.04873944, -0.01763833, -0.00664655,
          0.03444407, -0.00357095, -0.04538939, -0.0094085 ,
          0.03327018,  0.013641  ],
        [ 0.01725342, -0.04874995, -0.00608445, -0.03132888,
         -0.00135081, -0.00245364,  0.04202305,  0.0439891 ,
         -0.03451274, -0.01171521],
        [-0.01199137, -0.03247919, -0.00338144, -0.0235675 ,
          0.03697643, -0.04460119,  0.01563675,  0.03261742,
         -0.02669712, -0.0499821 ],
        [ 0.00364297,  0.01089319,  0.00324144,  0.0